name: StockRegression
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.11
  - matplotlib
  - pytorch
  - pandas
  - scikit-learn
  - numpy
  - ipykernel
  - pytorch
  - pip
  - pip:
    - yfinance
